title: 'Sandaru'
description: 'My personal blog'
baseurl: ''
url: 'https://darumaka.github.io'
# Google Analytics
google_analytics: UA—XXXXXXXX-X
author:
  name: Darryl
  url: https://git.sr.ht/~darumaka
  email: mica.tui@proton.me
markdown: kramdown
include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
permalink: /:year-:month-:day/:title
paginate: 5
exclude: [Gemfile, Gemfile.lock]
nav:
  - title: Blog
    url: /archive
  - title: About
    url: /about

