title: 'Sandaru'
description: 'My personal blog'
baseurl: '/blog'
url: 'https://daru-san.github.io/blog'
version: 1.0.0
# Google Analytics
google_analytics: UA—XXXXXXXX-X
# Author
author:
  name: Darryl
  url: https://git.sr.ht/~darumaka
  email: mica.tui@proton.me
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
permalink: /:year-:month-:day/:title
paginate: 5
paginate_path: '/baseurl/page:num/'
nav:
  - title: Blog
    url: /blog/archive
  - title: About
    url: /blog/about
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
